import Head from "next/head";
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';
const SEO = ({ pageTitle }) => (
  <>
    <Head>
      <title> {pageTitle && `AsparrowTech - Technology & IT Solutions React Next js Template`}</title>
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <meta name="description" content="Generated by create next app" />
      <meta name="robots" content="noindex, follow" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <link rel="icon" href="/asparrow-favicon.png" />
      <Analytics />
        <SpeedInsights />
    </Head>
  </>
);
 
export default SEO;
